/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactMessage = IDL.Record({
  'domainId' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Domain = IDL.Record({
  'id' : IDL.Nat,
  'afternicLink' : IDL.Text,
  'name' : IDL.Text,
  'registrar' : IDL.Text,
  'spaceshipLink' : IDL.Text,
  'price' : IDL.Float64,
  'atomLink' : IDL.Text,
});
export const Offer = IDL.Record({
  'domainId' : IDL.Nat,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'contactSeller' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getDomainById' : IDL.Func([IDL.Nat], [IDL.Opt(Domain)], ['query']),
  'getDomains' : IDL.Func([], [IDL.Vec(Domain)], ['query']),
  'getOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'initStore' : IDL.Func([], [], []),
  'submitOffer' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactMessage = IDL.Record({
    'domainId' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Domain = IDL.Record({
    'id' : IDL.Nat,
    'afternicLink' : IDL.Text,
    'name' : IDL.Text,
    'registrar' : IDL.Text,
    'spaceshipLink' : IDL.Text,
    'price' : IDL.Float64,
    'atomLink' : IDL.Text,
  });
  const Offer = IDL.Record({
    'domainId' : IDL.Nat,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'contactSeller' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getDomainById' : IDL.Func([IDL.Nat], [IDL.Opt(Domain)], ['query']),
    'getDomains' : IDL.Func([], [IDL.Vec(Domain)], ['query']),
    'getOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'initStore' : IDL.Func([], [], []),
    'submitOffer' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };