/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'domainId' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Domain {
  'id' : bigint,
  'afternicLink' : string,
  'name' : string,
  'registrar' : string,
  'spaceshipLink' : string,
  'price' : number,
  'atomLink' : string,
}
export interface Offer {
  'domainId' : bigint,
  'email' : string,
  'timestamp' : bigint,
  'amount' : number,
}
export interface _SERVICE {
  'contactSeller' : ActorMethod<[bigint, string, string, string], boolean>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getDomainById' : ActorMethod<[bigint], [] | [Domain]>,
  'getDomains' : ActorMethod<[], Array<Domain>>,
  'getOffers' : ActorMethod<[], Array<Offer>>,
  'initStore' : ActorMethod<[], undefined>,
  'submitOffer' : ActorMethod<[bigint, number, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];